"""Populates the database with reference symptoms, OBD-II codes, faults,
and the weighted rules that link them for the diagnosis engine."""

import json

from database import get_connection, init_db, is_seeded

SYMPTOMS = [
    ("Engine won't start", "Engine"),
    ("Engine cranks but won't start", "Engine"),
    ("Rough idle", "Engine"),
    ("Engine stalls while driving", "Engine"),
    ("Loss of power or acceleration", "Engine"),
    ("Check engine light is on", "Engine"),
    ("Engine overheating", "Cooling"),
    ("Knocking or ticking noise from engine", "Engine"),
    ("Vehicle uses more fuel than usual", "Engine"),
    ("Dashboard lights flicker or dim", "Electrical"),
    ("Clicking noise when starting", "Electrical"),
    ("Battery warning light on", "Electrical"),
    ("Slow engine crank", "Electrical"),
    ("Squealing or grinding noise when braking", "Brakes"),
    ("Vehicle pulls to one side when braking", "Brakes"),
    ("Soft or spongy brake pedal", "Brakes"),
    ("Longer stopping distance", "Brakes"),
    ("Slipping gears or delayed shifting", "Transmission"),
    ("Reddish fluid leaking under the car", "Transmission"),
    ("Jerking or shuddering when shifting", "Transmission"),
    ("Steam or smoke from under the hood", "Cooling"),
    ("Sweet smell from engine bay", "Cooling"),
    ("Rotten egg smell from exhaust", "Exhaust"),
    ("Excessive exhaust smoke", "Exhaust"),
]

DTC_CODES = [
    ("P0100", "Mass or Volume Air Flow Circuit Malfunction", "Fuel/Air"),
    ("P0101", "Mass or Volume Air Flow Circuit Range/Performance", "Fuel/Air"),
    ("P0113", "Intake Air Temperature Circuit High Input", "Fuel/Air"),
    ("P0128", "Coolant Thermostat Malfunction", "Cooling"),
    ("P0171", "System Too Lean (Bank 1)", "Fuel/Air"),
    ("P0172", "System Too Rich (Bank 1)", "Fuel/Air"),
    ("P0174", "System Too Lean (Bank 2)", "Fuel/Air"),
    ("P0217", "Engine Overheat Condition", "Cooling"),
    ("P0300", "Random/Multiple Cylinder Misfire Detected", "Ignition"),
    ("P0301", "Cylinder 1 Misfire Detected", "Ignition"),
    ("P0302", "Cylinder 2 Misfire Detected", "Ignition"),
    ("P0303", "Cylinder 3 Misfire Detected", "Ignition"),
    ("P0304", "Cylinder 4 Misfire Detected", "Ignition"),
    ("P0325", "Knock Sensor Circuit Malfunction", "Sensors"),
    ("P0335", "Crankshaft Position Sensor Circuit Malfunction", "Sensors"),
    ("P0340", "Camshaft Position Sensor Circuit Malfunction", "Sensors"),
    ("P0401", "Exhaust Gas Recirculation Flow Insufficient", "Emissions"),
    ("P0420", "Catalyst System Efficiency Below Threshold (Bank 1)", "Emissions"),
    ("P0430", "Catalyst System Efficiency Below Threshold (Bank 2)", "Emissions"),
    ("P0440", "Evaporative Emission Control System Malfunction", "Emissions"),
    ("P0442", "EVAP System Leak Detected (Small Leak)", "Emissions"),
    ("P0455", "EVAP System Leak Detected (Large Leak)", "Emissions"),
    ("P0500", "Vehicle Speed Sensor Malfunction", "Sensors"),
    ("P0562", "System Voltage Low", "Electrical"),
    ("P0563", "System Voltage High", "Electrical"),
    ("P0606", "ECM/PCM Processor Fault", "Electrical"),
    ("P0700", "Transmission Control System Malfunction", "Transmission"),
    ("P0715", "Input/Turbine Speed Sensor Circuit Malfunction", "Transmission"),
    ("P0730", "Incorrect Gear Ratio", "Transmission"),
]

# Each fault links to symptoms and DTC codes with an integer weight (higher =
# stronger evidence). The engine sums matched weights against the fault's
# total possible weight to compute a confidence percentage.
FAULTS = [
    {
        "name": "Worn or Fouled Spark Plugs",
        "description": "Spark plugs are worn, fouled, or gapped incorrectly, causing incomplete combustion.",
        "severity": "Medium",
        "recommended_action": "Inspect and replace spark plugs; check ignition coils if plugs look fine.",
        "causal_explanation": "Spark plugs ignite the air-fuel mixture in each cylinder. When they're worn or fouled with carbon/oil deposits, the spark becomes weak or inconsistent, so some combustion cycles misfire. That's what shows up as rough idle, hesitation, and cylinder misfire codes like P0300-P0304, and it wastes fuel because unburned fuel gets pushed out with the exhaust.",
        "repair_steps": ["Locate the spark plugs (check your owner's manual for position).",
                          "Remove each plug and inspect the electrode for wear, carbon buildup, or oil fouling.",
                          "Check the gap against the manufacturer's spec and adjust if needed.",
                          "Replace any plug that is worn, cracked, or heavily fouled.",
                          "Torque plugs to spec and reconnect ignition coils/wires."],
        "difficulty": "DIY-Friendly",
        "estimated_cost": "$20 - $100 (parts)",
        "estimated_time": "30 - 60 minutes",
        "symptoms": [("Rough idle", 2), ("Loss of power or acceleration", 2),
                     ("Engine stalls while driving", 1), ("Check engine light is on", 1),
                     ("Vehicle uses more fuel than usual", 2)],
        "codes": [("P0300", 3), ("P0301", 2), ("P0302", 2), ("P0303", 2), ("P0304", 2)],
    },
    {
        "name": "Failing Ignition Coil",
        "description": "One or more ignition coils are failing to deliver a consistent spark.",
        "severity": "Medium",
        "recommended_action": "Test and replace the faulty ignition coil(s).",
        "causal_explanation": "Each ignition coil steps up battery voltage to create the spark for one or more cylinders. When a coil degrades, it can't deliver a strong enough spark, causing that cylinder to misfire. The ECU detects this and logs a cylinder-specific code (P0301-P0304), and the engine runs rough or stalls as a result.",
        "repair_steps": ["Locate the ignition coil(s), usually mounted directly above each spark plug.",
                          "Swap a suspected coil with one from another cylinder and see if the misfire code follows it.",
                          "Replace the faulty coil with a manufacturer-matched part.",
                          "Clear the fault code and test drive to confirm the misfire is gone."],
        "difficulty": "DIY-Friendly",
        "estimated_cost": "$40 - $150 per coil",
        "estimated_time": "30 - 45 minutes",
        "symptoms": [("Rough idle", 2), ("Engine stalls while driving", 2), ("Check engine light is on", 1)],
        "codes": [("P0300", 2), ("P0301", 3), ("P0302", 3), ("P0303", 3), ("P0304", 3)],
    },
    {
        "name": "Weak or Dying Battery",
        "description": "The battery is losing charge or can no longer hold a full charge.",
        "severity": "Low",
        "recommended_action": "Test battery voltage and load capacity; replace the battery if it fails.",
        "causal_explanation": "The battery supplies the burst of current needed to turn the starter motor and powers the electrical system before the alternator takes over. As it weakens, it can no longer hold enough charge, leading to slow cranking, clicking sounds, dimming lights, and eventually a no-start.",
        "repair_steps": ["Use a multimeter to check resting voltage (should read around 12.6V).",
                          "Have the battery load-tested at an auto parts store (often free).",
                          "Clean any corrosion from the battery terminals.",
                          "Replace the battery if it fails the load test or is older than 3-5 years."],
        "difficulty": "DIY-Friendly",
        "estimated_cost": "$100 - $250",
        "estimated_time": "15 - 30 minutes",
        "symptoms": [("Slow engine crank", 3), ("Clicking noise when starting", 2),
                     ("Dashboard lights flicker or dim", 2), ("Battery warning light on", 2),
                     ("Engine won't start", 2)],
        "codes": [("P0562", 2)],
    },
    {
        "name": "Failing Alternator",
        "description": "The alternator is not adequately recharging the battery while the engine runs.",
        "severity": "Medium",
        "recommended_action": "Test alternator output voltage; replace the alternator if charging is low.",
        "causal_explanation": "The alternator recharges the battery and powers the electrical system while the engine runs. If its output drops, the battery slowly drains even while driving, causing flickering/dimming lights, a battery warning light, and eventually a stall once voltage gets too low.",
        "repair_steps": ["Start the engine and measure voltage at the battery terminals (should read 13.5-14.5V).",
                          "Inspect the alternator belt for wear, cracking, or looseness.",
                          "Check wiring connections at the alternator for corrosion.",
                          "Replace the alternator if output stays low with a battery that tests fine."],
        "difficulty": "Mechanic Recommended",
        "estimated_cost": "$300 - $600 (parts + labor)",
        "estimated_time": "1 - 2 hours",
        "symptoms": [("Dashboard lights flicker or dim", 3), ("Battery warning light on", 3),
                     ("Slow engine crank", 1), ("Engine stalls while driving", 1)],
        "codes": [("P0562", 2), ("P0563", 1)],
    },
    {
        "name": "Faulty Starter Motor",
        "description": "The starter motor or solenoid is failing to turn the engine over.",
        "severity": "Medium",
        "recommended_action": "Inspect and test the starter motor and solenoid; replace if faulty.",
        "causal_explanation": "The starter motor physically turns the engine over to begin combustion. A failing starter or solenoid can't engage properly, producing a clicking sound instead of a crank, or turning over slowly or not at all, separate from a battery issue if battery voltage tests fine.",
        "repair_steps": ["Confirm the battery and connections are good first (rule out a battery issue).",
                          "Listen for a single click (solenoid) vs rapid clicking (often battery) vs silence.",
                          "Have the starter motor tested on or off the vehicle.",
                          "Replace the starter motor if it's confirmed faulty."],
        "difficulty": "Mechanic Recommended",
        "estimated_cost": "$150 - $400 (parts + labor)",
        "estimated_time": "1 - 2 hours",
        "symptoms": [("Clicking noise when starting", 3), ("Engine cranks but won't start", 2),
                     ("Engine won't start", 2)],
        "codes": [],
    },
    {
        "name": "Clogged Fuel Filter",
        "description": "A clogged fuel filter is restricting fuel flow to the engine.",
        "severity": "Medium",
        "recommended_action": "Replace the fuel filter and inspect the fuel system for contamination.",
        "causal_explanation": "The fuel filter removes debris before fuel reaches the engine. As it clogs, fuel flow is restricted, so the engine gets less fuel than it needs under load, causing hesitation, stalling, and difficulty starting, and getting worse as clogging progresses.",
        "repair_steps": ["Locate the fuel filter (inline or inside the fuel tank, depending on the vehicle).",
                          "Relieve fuel system pressure before disconnecting any lines.",
                          "Replace the filter with the correct part for your vehicle.",
                          "Start the engine and check for leaks at the new connections."],
        "difficulty": "Mechanic Recommended",
        "estimated_cost": "$50 - $200",
        "estimated_time": "30 - 90 minutes",
        "symptoms": [("Loss of power or acceleration", 2), ("Engine stalls while driving", 2),
                     ("Rough idle", 1), ("Engine cranks but won't start", 1)],
        "codes": [("P0171", 2), ("P0174", 1)],
    },
    {
        "name": "Failing Fuel Pump",
        "description": "The fuel pump cannot maintain adequate fuel pressure.",
        "severity": "High",
        "recommended_action": "Test fuel pressure; replace the fuel pump if pressure is below spec.",
        "causal_explanation": "The fuel pump delivers fuel from the tank to the engine at the pressure it needs. A weakening pump can't maintain that pressure, especially under acceleration or load, causing stalling, hard starts, and loss of power, and can leave you stranded if it fails completely.",
        "repair_steps": ["Test fuel pressure at the fuel rail with a pressure gauge and compare to spec.",
                          "Listen for the fuel pump priming sound (a brief hum) when the key is turned to 'on'.",
                          "Check the fuel pump relay and fuse before condemning the pump itself.",
                          "Replace the fuel pump if pressure is confirmed low."],
        "difficulty": "Professional Required",
        "estimated_cost": "$400 - $800 (parts + labor)",
        "estimated_time": "2 - 4 hours",
        "symptoms": [("Engine cranks but won't start", 2), ("Engine stalls while driving", 2),
                     ("Loss of power or acceleration", 2)],
        "codes": [("P0171", 1), ("P0174", 1)],
    },
    {
        "name": "Low Engine Oil or Oil Leak",
        "description": "Engine oil level is low or leaking, risking severe engine wear.",
        "severity": "Critical",
        "recommended_action": "Check oil level immediately, inspect for leaks, and top up or repair before driving further.",
        "causal_explanation": "Oil lubricates and cools moving metal parts inside the engine. When the level runs low, metal-on-metal contact increases, producing knocking/ticking noises, and if unaddressed can cause catastrophic engine damage. Blue exhaust smoke can indicate oil is being burned internally.",
        "repair_steps": ["Check the oil level with the dipstick on level ground, engine off.",
                          "Look under the car and around the engine for visible oil leaks or wet spots.",
                          "Top up oil to the correct level if low (do not overfill).",
                          "Have a mechanic pressure-test and locate the source of any leak."],
        "difficulty": "DIY-Friendly (checking) / Mechanic Recommended (leak repair)",
        "estimated_cost": "$0 - $50 (top-up) / $150+ (leak repair)",
        "estimated_time": "10 minutes (check) / varies (repair)",
        "symptoms": [("Knocking or ticking noise from engine", 3), ("Engine overheating", 1),
                     ("Excessive exhaust smoke", 2)],
        "codes": [],
    },
    {
        "name": "Low Coolant or Coolant Leak",
        "description": "Coolant level is low or leaking, reducing the engine's ability to regulate temperature.",
        "severity": "High",
        "recommended_action": "Check coolant level, inspect hoses and radiator for leaks, and refill coolant.",
        "causal_explanation": "Coolant circulates through the engine and radiator to carry away heat. If the level drops, the engine can't shed heat properly, leading to overheating, steam from the hood, and a sweet smell as coolant vapor burns off tiny leaks.",
        "repair_steps": ["Let the engine cool completely before opening the coolant reservoir or radiator cap.",
                          "Check the coolant level against the min/max markings.",
                          "Inspect hoses, the radiator, and the water pump area for wet spots or stains.",
                          "Top up with the correct coolant type and have any leak repaired before driving further."],
        "difficulty": "DIY-Friendly (top-up) / Mechanic Recommended (leak repair)",
        "estimated_cost": "$20 - $50 (top-up) / $100 - $400 (leak repair)",
        "estimated_time": "15 minutes (check) / 1+ hours (repair)",
        "symptoms": [("Engine overheating", 3), ("Steam or smoke from under the hood", 3),
                     ("Sweet smell from engine bay", 2)],
        "codes": [("P0217", 2), ("P0128", 1)],
    },
    {
        "name": "Faulty Thermostat",
        "description": "The thermostat is stuck open or closed, disrupting engine temperature regulation.",
        "severity": "Medium",
        "recommended_action": "Replace the thermostat if it is stuck open or closed.",
        "causal_explanation": "The thermostat regulates coolant flow to keep engine temperature in the optimal range. If it sticks closed, coolant can't circulate and the engine overheats quickly; if stuck open, the engine may run cooler than normal and trigger a code.",
        "repair_steps": ["Confirm coolant level is adequate (rule out a low-coolant cause first).",
                          "Feel the upper radiator hose after warming up — it should get hot once the thermostat opens.",
                          "Replace the thermostat if it fails to open (hose stays cool) or is stuck open.",
                          "Refill and bleed the cooling system after replacement."],
        "difficulty": "Mechanic Recommended",
        "estimated_cost": "$50 - $200 (parts + labor)",
        "estimated_time": "1 hour",
        "symptoms": [("Engine overheating", 2)],
        "codes": [("P0128", 3), ("P0217", 1)],
    },
    {
        "name": "Failing Water Pump",
        "description": "The water pump is no longer circulating coolant effectively.",
        "severity": "High",
        "recommended_action": "Inspect the water pump for leaks or bearing wear; replace if faulty.",
        "causal_explanation": "The water pump circulates coolant through the engine and radiator. A failing pump (worn bearing or leaking seal) reduces coolant flow, causing overheating, and often leaks visible coolant near the front of the engine, sometimes with a whining noise from the bearing.",
        "repair_steps": ["Check for coolant leaking near the water pump pulley/weep hole.",
                          "Listen for grinding or whining from the pump pulley while the engine runs.",
                          "Replace the water pump (often along with the timing belt if pump-driven).",
                          "Refill coolant and bleed the system, then check for leaks."],
        "difficulty": "Professional Required",
        "estimated_cost": "$300 - $700 (parts + labor)",
        "estimated_time": "2 - 4 hours",
        "symptoms": [("Engine overheating", 2), ("Steam or smoke from under the hood", 2),
                     ("Sweet smell from engine bay", 1)],
        "codes": [("P0217", 1)],
    },
    {
        "name": "Worn Brake Pads",
        "description": "Brake pads are worn thin and need replacement.",
        "severity": "Medium",
        "recommended_action": "Inspect brake pad thickness and replace worn pads.",
        "causal_explanation": "Brake pads create friction against the rotor to slow the car. As the friction material wears down, a metal wear indicator starts contacting the rotor, producing a squeal, and eventually reduces stopping power if not replaced in time.",
        "repair_steps": ["Check pad thickness through the wheel spokes or by removing the wheel (replace under ~3mm).",
                          "Inspect the rotor surface for scoring or unevenness.",
                          "Replace pads on both sides of an axle together, never just one side.",
                          "Bed in new pads with a few gentle stops before hard braking."],
        "difficulty": "DIY-Friendly",
        "estimated_cost": "$50 - $150 per axle",
        "estimated_time": "45 - 90 minutes",
        "symptoms": [("Squealing or grinding noise when braking", 3), ("Longer stopping distance", 1)],
        "codes": [],
    },
    {
        "name": "Warped Brake Rotors",
        "description": "Brake rotors are warped, causing uneven braking.",
        "severity": "Medium",
        "recommended_action": "Inspect rotors for warping and resurface or replace as needed.",
        "causal_explanation": "Rotors can warp from repeated heat cycling (hard braking, towing) or uneven wear. A warped rotor causes the brake pad to grip unevenly around its surface, producing pulsation, pulling to one side, or a grinding/squealing noise during braking.",
        "repair_steps": ["Feel for pulsation in the brake pedal or steering wheel while braking.",
                          "Measure rotor thickness and run-out with a dial indicator if available.",
                          "Resurface the rotor if within spec thickness, or replace if too thin or heavily warped.",
                          "Replace pads at the same time if they show uneven wear."],
        "difficulty": "Mechanic Recommended",
        "estimated_cost": "$150 - $400 per axle",
        "estimated_time": "1 - 2 hours",
        "symptoms": [("Vehicle pulls to one side when braking", 2), ("Squealing or grinding noise when braking", 1)],
        "codes": [],
    },
    {
        "name": "Low or Leaking Brake Fluid",
        "description": "Brake fluid is low or leaking, reducing braking effectiveness.",
        "severity": "Critical",
        "recommended_action": "Check brake fluid level and inspect for leaks; have the brake system inspected immediately.",
        "causal_explanation": "Brake fluid transmits the force from the pedal to the brakes hydraulically. If the level drops or air enters from a leak, the pedal feels soft/spongy and stopping distance increases because pressure isn't transmitted efficiently — this is a safety-critical issue.",
        "repair_steps": ["Check the brake fluid reservoir level against the min/max lines.",
                          "Inspect brake lines, calipers, and wheel cylinders for visible fluid leaks.",
                          "Top up with the correct fluid type only if no leak is found (a drop usually means a leak).",
                          "Have the brake system inspected and bled immediately — do not drive if the pedal feels unsafe."],
        "difficulty": "Professional Required",
        "estimated_cost": "$100 - $400",
        "estimated_time": "1 - 2 hours",
        "symptoms": [("Soft or spongy brake pedal", 3), ("Longer stopping distance", 2)],
        "codes": [],
    },
    {
        "name": "Faulty Oxygen (O2) Sensor",
        "description": "The oxygen sensor is giving inaccurate readings, throwing off the fuel mixture.",
        "severity": "Medium",
        "recommended_action": "Test and replace the faulty oxygen sensor.",
        "causal_explanation": "The O2 sensor measures unburned oxygen in the exhaust so the ECU can fine-tune the air-fuel mixture. A faulty sensor sends inaccurate readings, causing the engine to run too rich or lean — wasting fuel, causing rough idle, and triggering related fault codes.",
        "repair_steps": ["Locate the O2 sensor(s) on the exhaust pipe before and after the catalytic converter.",
                          "Check wiring and connectors for damage before replacing the sensor.",
                          "Replace the faulty sensor with the correct type for its position (upstream/downstream).",
                          "Clear the code and monitor fuel trims to confirm the fix."],
        "difficulty": "DIY-Friendly",
        "estimated_cost": "$50 - $250",
        "estimated_time": "30 - 60 minutes",
        "symptoms": [("Vehicle uses more fuel than usual", 2), ("Check engine light is on", 1), ("Rough idle", 1)],
        "codes": [("P0171", 2), ("P0172", 2), ("P0174", 1)],
    },
    {
        "name": "Failing Catalytic Converter",
        "description": "The catalytic converter's efficiency has dropped below acceptable limits.",
        "severity": "High",
        "recommended_action": "Inspect the catalytic converter and exhaust system; replace if efficiency is below threshold.",
        "causal_explanation": "The catalytic converter converts harmful exhaust gases into less harmful ones. When its internal catalyst degrades, conversion efficiency drops below the threshold the ECU expects, triggering P0420/P0430, and can also produce a rotten-egg smell and reduced power from exhaust restriction.",
        "repair_steps": ["Rule out an upstream cause first (misfires or a bad O2 sensor can damage the converter).",
                          "Check for a rotten-egg smell and any physical rattling from the converter (indicates internal damage).",
                          "Have a mechanic verify efficiency with a scan tool before replacing (it's an expensive part).",
                          "Replace the catalytic converter if confirmed faulty."],
        "difficulty": "Professional Required",
        "estimated_cost": "$500 - $2,500",
        "estimated_time": "2 - 3 hours",
        "symptoms": [("Loss of power or acceleration", 1), ("Rotten egg smell from exhaust", 3),
                     ("Check engine light is on", 1)],
        "codes": [("P0420", 3), ("P0430", 3)],
    },
    {
        "name": "Vacuum Leak (Intake)",
        "description": "An intake vacuum leak is letting unmetered air into the engine.",
        "severity": "Medium",
        "recommended_action": "Inspect intake hoses and gaskets for cracks or leaks and repair.",
        "causal_explanation": "The intake system relies on a sealed vacuum to accurately meter air entering the engine. A crack or loose hose lets in unmetered air, leaning out the air-fuel mixture, causing rough/high idle, hesitation, and lean-condition codes like P0171/P0174.",
        "repair_steps": ["Listen for a hissing sound near intake hoses and gaskets with the engine running.",
                          "Spray a small amount of soapy water around suspected areas — an idle change indicates the leak location.",
                          "Replace or reseat any cracked hose, loose clamp, or damaged gasket.",
                          "Clear codes and monitor idle behavior to confirm the leak is fixed."],
        "difficulty": "Mechanic Recommended",
        "estimated_cost": "$50 - $250",
        "estimated_time": "1 - 2 hours",
        "symptoms": [("Rough idle", 2), ("Engine stalls while driving", 1), ("Vehicle uses more fuel than usual", 1)],
        "codes": [("P0171", 2), ("P0174", 2), ("P0101", 1)],
    },
    {
        "name": "Worn Transmission Fluid or Failing Transmission",
        "description": "Transmission fluid is degraded or the transmission itself is failing.",
        "severity": "High",
        "recommended_action": "Check transmission fluid level and condition; have the transmission inspected.",
        "causal_explanation": "Transmission fluid lubricates internal components and enables hydraulic gear-shifting. Degraded or low fluid causes rough, delayed, or slipping shifts as hydraulic pressure and lubrication drop — left unaddressed, this accelerates internal wear toward full transmission failure.",
        "repair_steps": ["Check transmission fluid level and color (should not be dark or burnt-smelling).",
                          "Look under the car for reddish fluid leaking near the transmission.",
                          "Have the fluid and filter changed if it's overdue or degraded.",
                          "Get a full transmission inspection if slipping/jerking continues after a fluid change."],
        "difficulty": "Professional Required",
        "estimated_cost": "$150 - $300 (fluid service) / $1,500+ (transmission repair)",
        "estimated_time": "1 hour (service) / days (major repair)",
        "symptoms": [("Slipping gears or delayed shifting", 3), ("Reddish fluid leaking under the car", 2),
                     ("Jerking or shuddering when shifting", 2)],
        "codes": [("P0700", 2), ("P0715", 1), ("P0730", 2)],
    },
    {
        "name": "Faulty Mass Airflow (MAF) Sensor",
        "description": "The mass airflow sensor is sending incorrect readings to the engine computer.",
        "severity": "Medium",
        "recommended_action": "Clean or replace the mass airflow sensor.",
        "causal_explanation": "The MAF sensor measures incoming air volume so the ECU can calculate the right amount of fuel to inject. A dirty or failing sensor sends incorrect readings, causing rough idle, hesitation, and poor fuel economy as the engine gets the wrong fuel mixture.",
        "repair_steps": ["Locate the MAF sensor in the intake tube near the air filter box.",
                          "Carefully clean it with a dedicated MAF sensor cleaner (do not touch the sensing wires).",
                          "Check for a cracked or poorly sealed intake tube nearby.",
                          "Replace the sensor if cleaning doesn't resolve the codes/symptoms."],
        "difficulty": "DIY-Friendly",
        "estimated_cost": "$10 (cleaner) / $80 - $250 (replacement)",
        "estimated_time": "20 - 40 minutes",
        "symptoms": [("Rough idle", 1), ("Loss of power or acceleration", 1), ("Vehicle uses more fuel than usual", 1)],
        "codes": [("P0100", 3), ("P0101", 2)],
    },
    {
        "name": "Loose or Damaged Gas Cap (EVAP Leak)",
        "description": "A loose or damaged gas cap is letting fuel vapor escape, triggering an EVAP leak code.",
        "severity": "Low",
        "recommended_action": "Check that the gas cap is tight and undamaged; replace if cracked.",
        "causal_explanation": "The gas cap seals the fuel tank to maintain pressure in the evaporative emissions system. A loose or cracked cap lets vapor escape, and the ECU detects the pressure change as a leak, triggering an EVAP code and the check engine light.",
        "repair_steps": ["Check that the gas cap clicks fully when tightened.",
                          "Inspect the cap's rubber seal for cracks or debris.",
                          "Replace the gas cap if damaged (a common and cheap fix).",
                          "Drive for a few days — the check engine light may take several trips to clear on its own."],
        "difficulty": "DIY-Friendly",
        "estimated_cost": "$10 - $25",
        "estimated_time": "5 minutes",
        "symptoms": [("Check engine light is on", 1)],
        "codes": [("P0440", 2), ("P0442", 2), ("P0455", 3)],
    },
]


def seed():
    init_db()
    if is_seeded():
        print("Database already seeded, skipping.")
        return

    conn = get_connection()
    cur = conn.cursor()

    symptom_ids = {}
    for name, category in SYMPTOMS:
        cur.execute("INSERT INTO symptoms (name, category) VALUES (?, ?)", (name, category))
        symptom_ids[name] = cur.lastrowid

    code_ids = {}
    for code, description, category in DTC_CODES:
        cur.execute("INSERT INTO dtc_codes (code, description, category) VALUES (?, ?, ?)",
                    (code, description, category))
        code_ids[code] = cur.lastrowid

    for fault in FAULTS:
        cur.execute(
            "INSERT INTO faults (name, description, severity, recommended_action, "
            "causal_explanation, repair_steps_json, difficulty, estimated_cost, estimated_time) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
            (
                fault["name"],
                fault["description"],
                fault["severity"],
                fault["recommended_action"],
                fault["causal_explanation"],
                json.dumps(fault["repair_steps"]),
                fault["difficulty"],
                fault["estimated_cost"],
                fault["estimated_time"],
            ),
        )
        fault_id = cur.lastrowid

        for symptom_name, weight in fault["symptoms"]:
            cur.execute(
                "INSERT INTO fault_symptoms (fault_id, symptom_id, weight) VALUES (?, ?, ?)",
                (fault_id, symptom_ids[symptom_name], weight),
            )

        for code, weight in fault["codes"]:
            cur.execute(
                "INSERT INTO fault_dtc_codes (fault_id, dtc_code_id, weight) VALUES (?, ?, ?)",
                (fault_id, code_ids[code], weight),
            )

    conn.commit()
    conn.close()
    print(f"Seeded {len(SYMPTOMS)} symptoms, {len(DTC_CODES)} DTC codes, {len(FAULTS)} faults.")


if __name__ == "__main__":
    seed()
